#!/bin/bash

sudo date

PREFIX='sudo service'

if [ -z '$1' ]; then
while true; do
    read -p "Do you wish to install this program?" yn
    case $yn in
        [Yy]* ) COMMAND='start'; break;;
        [Nn]* ) COMMAND='stop'; break;;
        * ) echo "Please answer yes or no.";;
    esac
done	
else
	COMMAND=$1;
fi

$PREFIX nginx $COMMAND; sleep 1;
$PREFIX mysql $COMMAND; sleep 1;
$PREFIX memcached $COMMAND; sleep 1;
$PREFIX mongodb $COMMAND; sleep 1;
$PREFIX php5-fpm $COMMAND; sleep 1;
$PREFIX redis-server $COMMAND; sleep 1;
